In [1]:
import numpy as np

In [5]:
new=np.array([[1,2,3,4],
             [1,2,3,4],
             [1,2,3,4]])

In [6]:
print(new)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [9]:
new=np.eye(3,5)

In [10]:
print(new)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [12]:
newone=np.ones((3,5))
print(newone)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
newzero=np.zeros((3,2,2))
print(newzero) #3D array with 2X2 dimensions

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
