In [ ]:
import numpy as np

: 

In [ ]:
new=np.array([[1,2,3,4],
             [1,2,3,4],
             [1,2,3,4]])

: 

In [ ]:
print(new)

: 

In [9]:
new=np.eye(3,5)

In [10]:
print(new)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
newone=np.ones((3,5))
print(newone)

: 

In [ ]:
newzero=np.zeros((3,2,2))
print(newzero) #3D array with 2X2 dimensions

: 